Repository DrLAlbertoAngelesH/EstudioDelTrabajoII-2024-1, pull requests merged in 2024-03, with the labels that each got.

#21 Diego guadalupe gomez hernandez
  README.md
Labels: question

#34 se agrego diapositivas
  Diapositivas/sema-5/12-03-24.pdf
Labels: documentation

#72 advertencia
  README.md
Labels: bug, wontfix
